package cms

import (
	"crypto/x509"
	"encoding/pem"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestInterop_OpenSSL verifies that this library correctly parses and verifies
// CMS SignedData messages produced by OpenSSL. Fixtures are pre-generated by
// testdata/openssl/regen.sh and committed to the repository; regenerating them
// requires OpenSSL 3.0+, but running this test does not.
func TestInterop_OpenSSL(t *testing.T) {
	rsaCACert := parseFixtureCert(t, "testdata/openssl/signed/rsa_ca.cert.pem")
	ecP256CACert := parseFixtureCert(t, "testdata/openssl/signed/ec_p256_ca.cert.pem")
	ecP384CACert := parseFixtureCert(t, "testdata/openssl/signed/ec_p384_ca.cert.pem")
	ecP521CACert := parseFixtureCert(t, "testdata/openssl/signed/ec_p521_ca.cert.pem")

	content, err := os.ReadFile("testdata/content.bin")
	require.NoError(t, err)

	tests := []struct {
		name     string
		fixture  string
		cert     *x509.Certificate
		detached bool
	}{
		{
			name:    "attached RSA PKCS1v15 SHA-256",
			fixture: "testdata/openssl/signed/attached_rsa_pkcs1_sha256.der",
			cert:    rsaCACert,
		},
		{
			name:     "detached RSA PKCS1v15 SHA-256",
			fixture:  "testdata/openssl/signed/detached_rsa_pkcs1_sha256.der",
			cert:     rsaCACert,
			detached: true,
		},
		{
			name:    "attached RSA-PSS SHA-256",
			fixture: "testdata/openssl/signed/attached_rsa_pss_sha256.der",
			cert:    rsaCACert,
		},
		{
			name:    "attached RSA-PSS SHA-384",
			fixture: "testdata/openssl/signed/attached_rsa_pss_sha384.der",
			cert:    rsaCACert,
		},
		{
			name:    "attached RSA-PSS SHA-512",
			fixture: "testdata/openssl/signed/attached_rsa_pss_sha512.der",
			cert:    rsaCACert,
		},
		{
			name:    "attached ECDSA P-256 SHA-256",
			fixture: "testdata/openssl/signed/attached_ec_p256_sha256.der",
			cert:    ecP256CACert,
		},
		{
			name:     "detached ECDSA P-256 SHA-256",
			fixture:  "testdata/openssl/signed/detached_ec_p256_sha256.der",
			cert:     ecP256CACert,
			detached: true,
		},
		{
			name:    "attached ECDSA P-384 SHA-384",
			fixture: "testdata/openssl/signed/attached_ec_p384_sha384.der",
			cert:    ecP384CACert,
		},
		{
			name:    "attached ECDSA P-521 SHA-512",
			fixture: "testdata/openssl/signed/attached_ec_p521_sha512.der",
			cert:    ecP521CACert,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			der, err := os.ReadFile(tt.fixture)
			require.NoError(t, err)

			pool := x509.NewCertPool()
			pool.AddCert(tt.cert)
			opts := []VerifyOption{WithTrustRoots(pool)}

			psd, err := ParseSignedData(FromBytes(der))
			require.NoError(t, err)

			assert.Equal(t, tt.detached, psd.IsDetached())

			if tt.detached {
				require.NoError(t, psd.VerifyDetached(FromBytes(content), opts...))
			} else {
				require.NoError(t, psd.Verify(opts...))
			}
		})
	}
}

// parseFixtureCert reads a PEM-encoded certificate from path and returns the
// parsed *x509.Certificate. Fails the test immediately on any error.
func parseFixtureCert(t *testing.T, path string) *x509.Certificate {
	t.Helper()
	pemBytes, err := os.ReadFile(path)
	require.NoError(t, err)
	block, _ := pem.Decode(pemBytes)
	require.NotNil(t, block, "no PEM block found in %s", path)
	cert, err := x509.ParseCertificate(block.Bytes)
	require.NoError(t, err)
	return cert
}
