package cms

import (
	"crypto/x509"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestInterop_EdgeCases verifies that the library correctly parses and verifies
// hand-crafted CMS SignedData fixtures that exercise non-standard but RFC-legal
// encodings. Fixtures are generated by testdata/edge_cases/gen.go and committed
// to the repository; running this test does not require any external tool.
func TestInterop_EdgeCases(t *testing.T) {
	signerCert := parseFixtureCert(t, "testdata/edge_cases/rsa_signer.cert.pem")
	content, err := os.ReadFile("testdata/content.bin")
	require.NoError(t, err)
	_ = content // used only in ber_constructed_octet description

	// Default trust pool: most fixtures are signed by the key in rsa_signer.cert.pem.
	defaultPool := x509.NewCertPool()
	defaultPool.AddCert(signerCert)
	defaultOpts := []VerifyOption{WithTrustRoots(defaultPool)}

	tests := []struct {
		name        string
		fixture     string
		opts        func(t *testing.T, psd *ParsedSignedData) []VerifyOption
		extraChecks func(t *testing.T, psd *ParsedSignedData)
	}{
		{
			// RFC 5754 §2: SHA-256 AlgID SHOULD have absent parameters, but a receiver
			// MUST accept NULL when present. Used by Bouncy Castle and some HSMs.
			name:    "SHA-256 digestAlgorithm with explicit NULL parameters",
			fixture: "testdata/edge_cases/sha256_null_params.der",
		},
		{
			// RFC 4055 §3.3: RSASSA-PSS-params trailerField [3] INTEGER 1 is the default
			// but is commonly encoded explicitly by Bouncy Castle and OpenSSL. The parser
			// must accept it. All four optional RSASSA-PSS-params fields are present.
			name:    "RSA-PSS with trailerField explicit",
			fixture: "testdata/edge_cases/rsa_pss_trailer_explicit.der",
		},
		{
			// saltLength=20 (the SHA-1 default) used with SHA-256. Legal per RFC 4055.
			// Verifier must read the saltLength from RSASSA-PSS-params rather than
			// substituting the hash output size.
			name:    "RSA-PSS with non-standard saltLength=20",
			fixture: "testdata/edge_cases/rsa_pss_saltlen_20.der",
		},
		{
			// certificates [0] field is present but contains an empty SET. Must not be
			// confused with the field being absent. Signer cert supplied out-of-band.
			name:    "empty certificates SET present",
			fixture: "testdata/edge_cases/empty_certificates_set.der",
			opts: func(t *testing.T, _ *ParsedSignedData) []VerifyOption {
				t.Helper()
				// Bag is empty; supply the signer cert as an external certificate so
				// findSignerCert can locate it, and add it to the trust pool.
				return []VerifyOption{
					WithExternalCertificates(signerCert),
					WithTrustRoots(defaultPool),
				}
			},
		},
		{
			// certificates bag contains the signer cert plus one unrelated cert. The
			// extra cert must be ignored; Signers() must return only the actual signer.
			name:    "extra unrelated certificate in bag",
			fixture: "testdata/edge_cases/extra_cert_in_bag.der",
			extraChecks: func(t *testing.T, psd *ParsedSignedData) {
				t.Helper()
				assert.Len(t, psd.Signers(), 1, "Signers() should return only the actual signer")
				assert.Len(t, psd.Certificates(), 2, "bag should contain signer cert plus extra cert")
			},
		},
		{
			// Outermost ContentInfo SEQUENCE encoded with BER indefinite length.
			// ParseSignedData calls ber.ToDER internally, so this must succeed.
			name:    "BER indefinite-length outer SEQUENCE",
			fixture: "testdata/edge_cases/ber_indefinite_outer.der",
		},
		{
			// The outermost ContentInfo SEQUENCE uses a non-minimal (padded) long-form
			// length encoding. DER requires the shortest form; BER allows leading zero
			// bytes in the multi-byte length. The BER normalizer must rewrite it.
			name:    "BER non-minimal (long-form) length encoding",
			fixture: "testdata/edge_cases/ber_long_form_lengths.der",
		},
		{
			// eContent OCTET STRING encoded as BER constructed (chunked) form: tag 0x24.
			// The BER normalizer must flatten it to a single primitive OCTET STRING
			// before digest verification. This encoding appears in some HSM outputs.
			name:    "BER constructed OCTET STRING for eContent",
			fixture: "testdata/edge_cases/ber_constructed_octet.der",
		},
		{
			// Two SignerInfos both using SHA-256. The digestAlgorithms SET must contain
			// SHA-256 exactly once per RFC 5652 §5.1 deduplication.
			name:    "multiple SignerInfos with SHA-256 deduplicated",
			fixture: "testdata/edge_cases/multi_signer_dedup.der",
			extraChecks: func(t *testing.T, psd *ParsedSignedData) {
				t.Helper()
				assert.Len(t, psd.Signers(), 2, "multi-signer fixture must have two SignerInfos")
			},
		},
		{
			// Signer cert has a 20-byte (160-bit) serial with the high bit set. The DER
			// INTEGER encoding requires a leading zero byte to keep the value positive.
			// IssuerAndSerialNumber matching must handle this correctly.
			name:    "large serial number in IssuerAndSerialNumber",
			fixture: "testdata/edge_cases/large_serial_number.der",
			opts: func(t *testing.T, psd *ParsedSignedData) []VerifyOption {
				t.Helper()
				// The signer cert (with the large serial) is embedded in the bag.
				// Extract it and use it as the trust root.
				certs := psd.Certificates()
				require.Len(t, certs, 1, "expected exactly one cert in bag")
				pool := x509.NewCertPool()
				pool.AddCert(certs[0])
				return []VerifyOption{WithTrustRoots(pool)}
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			der, err := os.ReadFile(tt.fixture)
			require.NoError(t, err)

			psd, err := ParseSignedData(FromBytes(der))
			require.NoError(t, err)

			opts := defaultOpts
			if tt.opts != nil {
				opts = tt.opts(t, psd)
			}

			require.NoError(t, psd.Verify(opts...))

			if tt.extraChecks != nil {
				tt.extraChecks(t, psd)
			}
		})
	}
}
