package cms

import (
	"crypto"
	"crypto/x509"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestInterop_BC_EnvelopedData verifies that this library correctly parses and
// decrypts CMS EnvelopedData messages that use Bouncy Castle encoding choices.
// Fixtures are generated by testdata/bc/gen.go and committed to the repository;
// running this test does not require any external tool.
func TestInterop_BC_EnvelopedData(t *testing.T) {
	rsaRecipCert := parseFixtureCert(t, "testdata/bc/enveloped/rsa_recip.cert.pem")
	rsaRecipKey := parseFixtureKey(t, "testdata/bc/enveloped/rsa_recip.key.pem")
	ecRecipCert := parseFixtureCert(t, "testdata/bc/enveloped/ec_p256_recip.cert.pem")
	ecRecipKey := parseFixtureKey(t, "testdata/bc/enveloped/ec_p256_recip.key.pem")

	content, err := os.ReadFile("testdata/content.bin")
	require.NoError(t, err)

	tests := []struct {
		name    string
		fixture string
		cert    *x509.Certificate
		key     crypto.PrivateKey
	}{
		{
			// BC uses explicit RSAESOAEPParams with SHA-256 for both the hash and
			// the mask-generation function. AES-256-CBC for content encryption.
			name:    "RSA-OAEP SHA-256 AES-256-CBC",
			fixture: "testdata/bc/enveloped/rsa_oaep_sha256_aes256cbc.der",
			cert:    rsaRecipCert,
			key:     rsaRecipKey,
		},
		{
			// ECDH P-256 key agreement with SHA-256 KDF and AES-128 key wrap,
			// AES-256-CBC content encryption.
			name:    "ECDH P-256 AES-256-CBC",
			fixture: "testdata/bc/enveloped/ec_p256_aes256cbc.der",
			cert:    ecRecipCert,
			key:     ecRecipKey,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			der, err := os.ReadFile(tt.fixture)
			require.NoError(t, err)

			ped, err := ParseEnvelopedData(FromBytes(der))
			require.NoError(t, err)

			plaintext, err := ped.Decrypt(tt.key, tt.cert)
			require.NoError(t, err)
			assert.Equal(t, content, plaintext)
		})
	}
}
