package cms

import (
	"crypto"
	"crypto/x509"
	"encoding/pem"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestInterop_OpenSSL_EnvelopedData verifies that this library correctly parses
// and decrypts CMS EnvelopedData messages produced by OpenSSL. Fixtures are
// pre-generated by testdata/openssl/regen.sh and committed to the repository;
// regenerating them requires OpenSSL 3.0+, but running this test does not.
//
// SHA-1 OAEP cases are expected to fail: OpenSSL uses SHA-1 as the default
// OAEP hash, but tryDecryptKTRI in envelopeddata.go hardcodes sha256.New().
// Those cases document the limitation rather than hiding it.
func TestInterop_OpenSSL_EnvelopedData(t *testing.T) {
	rsaRecipCert := parseFixtureCert(t, "testdata/openssl/enveloped/rsa_recip.cert.pem")
	rsaRecipKey := parseFixtureKey(t, "testdata/openssl/enveloped/rsa_recip.key.pem")
	ecP256RecipCert := parseFixtureCert(t, "testdata/openssl/enveloped/ec_p256_recip.cert.pem")
	ecP256RecipKey := parseFixtureKey(t, "testdata/openssl/enveloped/ec_p256_recip.key.pem")

	content, err := os.ReadFile("testdata/content.bin")
	require.NoError(t, err)

	tests := []struct {
		name    string
		fixture string
		cert    *x509.Certificate
		key     crypto.PrivateKey
		wantErr bool
	}{
		// SHA-1 OAEP: OpenSSL's default when -keyopt rsa_padding_mode:oaep is set
		// without -keyopt rsa_oaep_md:sha256. The library hardcodes sha256.New() in
		// tryDecryptKTRI rather than reading the hash from the AlgorithmIdentifier
		// parameters, so decryption fails. Tracked as a known limitation.
		{
			name:    "RSA-OAEP SHA-1 AES-256-CBC [known failure: library hardcodes SHA-256 OAEP]",
			fixture: "testdata/openssl/enveloped/rsa_oaep_sha1_aes256cbc.der",
			cert:    rsaRecipCert,
			key:     rsaRecipKey,
			wantErr: true,
		},
		{
			name:    "RSA-OAEP SHA-1 AES-128-CBC [known failure: library hardcodes SHA-256 OAEP]",
			fixture: "testdata/openssl/enveloped/rsa_oaep_sha1_aes128cbc.der",
			cert:    rsaRecipCert,
			key:     rsaRecipKey,
			wantErr: true,
		},
		// SHA-256 OAEP: generated with -keyopt rsa_oaep_md:sha256. The library
		// can decrypt this today.
		{
			name:    "RSA-OAEP SHA-256 AES-256-CBC",
			fixture: "testdata/openssl/enveloped/rsa_oaep_sha256_aes256cbc.der",
			cert:    rsaRecipCert,
			key:     rsaRecipKey,
		},
		// ECDH P-256: key agreement via dhSinglePass-stdDH-sha256kdf-scheme,
		// AES-128 key wrap, AES-256-CBC content encryption.
		{
			name:    "ECDH P-256 AES-256-CBC",
			fixture: "testdata/openssl/enveloped/ec_p256_aes256cbc.der",
			cert:    ecP256RecipCert,
			key:     ecP256RecipKey,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			der, err := os.ReadFile(tt.fixture)
			require.NoError(t, err)

			ped, err := ParseEnvelopedData(FromBytes(der))
			require.NoError(t, err)

			plaintext, err := ped.Decrypt(tt.key, tt.cert)
			if tt.wantErr {
				assert.Error(t, err)
				return
			}
			require.NoError(t, err)
			assert.Equal(t, content, plaintext)
		})
	}
}

// parseFixtureKey reads a PEM-encoded PKCS#8 private key from path and returns
// the parsed crypto.PrivateKey. Fails the test immediately on any error.
func parseFixtureKey(t *testing.T, path string) crypto.PrivateKey {
	t.Helper()
	pemBytes, err := os.ReadFile(path)
	require.NoError(t, err)
	block, _ := pem.Decode(pemBytes)
	require.NotNil(t, block, "no PEM block found in %s", path)
	key, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	require.NoError(t, err, "failed to parse private key from %s", path)
	return key
}
