package cms

import (
	"crypto/x509"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestInterop_BC_SignedData verifies that this library correctly parses and
// verifies CMS SignedData messages that use Bouncy Castle's encoding choices:
//   - digestAlgorithm AlgorithmIdentifier with explicit NULL parameters
//   - RSA PKCS1v15 signatureAlgorithm uses sha256WithRSAEncryption OID
//   - RSA-PSS RSASSA-PSS-params include trailerField=1 explicitly
//
// Fixtures are generated by testdata/bc/gen.go and committed to the repository;
// running this test does not require any external tool.
func TestInterop_BC_SignedData(t *testing.T) {
	rsaCert := parseFixtureCert(t, "testdata/bc/signed/rsa_signer.cert.pem")
	ecP256Cert := parseFixtureCert(t, "testdata/bc/signed/ec_p256_signer.cert.pem")
	ecP384Cert := parseFixtureCert(t, "testdata/bc/signed/ec_p384_signer.cert.pem")
	ed25519Cert := parseFixtureCert(t, "testdata/bc/signed/ed25519_signer.cert.pem")

	content, err := os.ReadFile("testdata/content.bin")
	require.NoError(t, err)

	tests := []struct {
		name        string
		fixture     string
		cert        *x509.Certificate
		detached    bool
		noCerts     bool
		extraChecks func(t *testing.T, psd *ParsedSignedData)
	}{
		{
			// BC uses sha256WithRSAEncryption (1.2.840.113549.1.1.11) as the
			// signatureAlgorithm OID, not rsaEncryption. digestAlgorithm has NULL params.
			name:    "attached RSA PKCS1v15 SHA-256 (BC OIDs)",
			fixture: "testdata/bc/signed/attached_rsa_pkcs1_sha256.der",
			cert:    rsaCert,
		},
		{
			name:     "detached RSA PKCS1v15 SHA-256 (BC OIDs)",
			fixture:  "testdata/bc/signed/detached_rsa_pkcs1_sha256.der",
			cert:     rsaCert,
			detached: true,
		},
		{
			// BC encodes RSA-PSS params with trailerField=1 explicit (RFC 4055 default).
			// Also adds NULL params to digestAlgorithm.
			name:    "attached RSA-PSS SHA-256 (trailerField explicit, NULL digest params)",
			fixture: "testdata/bc/signed/attached_rsa_pss_sha256.der",
			cert:    rsaCert,
		},
		{
			name:    "attached RSA-PSS SHA-384",
			fixture: "testdata/bc/signed/attached_rsa_pss_sha384.der",
			cert:    rsaCert,
		},
		{
			// BC includes NULL parameters in the digestAlgorithm AlgorithmIdentifier
			// for SHA-256 (RFC 5754 says SHOULD be absent but MUST accept NULL).
			name:    "attached ECDSA P-256 SHA-256 (NULL digest params)",
			fixture: "testdata/bc/signed/attached_ec_p256_sha256.der",
			cert:    ecP256Cert,
		},
		{
			name:    "attached ECDSA P-384 SHA-384",
			fixture: "testdata/bc/signed/attached_ec_p384_sha384.der",
			cert:    ecP384Cert,
		},
		{
			name:    "attached Ed25519",
			fixture: "testdata/bc/signed/attached_ed25519.der",
			cert:    ed25519Cert,
		},
		{
			// certificates bag contains the signer cert plus one extra unrelated cert.
			// Verify succeeds and Signers() returns exactly one entry.
			name:    "attached RSA PKCS1v15 SHA-256 with extra cert in chain bag",
			fixture: "testdata/bc/signed/attached_rsa_pkcs1_with_chain.der",
			cert:    rsaCert,
			extraChecks: func(t *testing.T, psd *ParsedSignedData) {
				t.Helper()
				assert.Len(t, psd.Signers(), 1)
				assert.Len(t, psd.Certificates(), 2, "bag should contain signer cert plus extra cert")
			},
		},
		{
			// certificates field absent. Signer cert supplied via WithExternalCertificates.
			name:    "attached RSA PKCS1v15 SHA-256 with no certificates field",
			fixture: "testdata/bc/signed/attached_rsa_pkcs1_no_certs.der",
			cert:    rsaCert,
			noCerts: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			der, err := os.ReadFile(tt.fixture)
			require.NoError(t, err)

			pool := x509.NewCertPool()
			pool.AddCert(tt.cert)
			opts := []VerifyOption{WithTrustRoots(pool)}
			if tt.noCerts {
				// Cert is absent from the bag; supply it for signer lookup.
				opts = append(opts, WithExternalCertificates(tt.cert))
			}

			psd, err := ParseSignedData(FromBytes(der))
			require.NoError(t, err)

			assert.Equal(t, tt.detached, psd.IsDetached())

			if tt.detached {
				require.NoError(t, psd.VerifyDetached(FromBytes(content), opts...))
			} else {
				require.NoError(t, psd.Verify(opts...))
			}

			if tt.extraChecks != nil {
				tt.extraChecks(t, psd)
			}
		})
	}
}
