.PHONY: test test-cover lint cover-report all help

# Run the full test suite.
test:
	go test ./... -count=1 -timeout=120s

# Run the test suite with coverage profiling across all packages.
test-cover:
	go test ./... -count=1 -timeout=120s -coverprofile=coverage.out -coverpkg=./...

# Open the HTML coverage report generated by test-cover.
cover-report: test-cover
	go tool cover -html=coverage.out -o coverage.html
	open coverage.html

# Run golangci-lint.
lint:
	golangci-lint run ./...

# Run lint then tests.
all: lint test

help:
	@echo "Targets:"
	@echo "  test          run the full test suite"
	@echo "  test-cover    run tests with coverage profiling"
	@echo "  cover-report  run tests with coverage and open the HTML report"
	@echo "  lint          run golangci-lint"
	@echo "  all           lint then test"
